image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - build
  - test
  - archive

test:
  stage: test
  script:
    - dotnet test --blame-hang-timeout 2m --logger "junit" $(find *.sln -print -quit)
  artifacts:
    when: always
    paths:
      - ./test/**/TestResults/
    reports:
      junit:
        - ./test/**/TestResults/TestResults.xml

archive image:
  image: docker:25.0.4-git
  services:
    - docker:25.0.3-dind
  stage: archive
  tags:
    - all
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -f $(find ./src/**/Dockerfile -print -quit) -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - if [ $(git diff HEAD HEAD~1 --name-only | grep VERSION) ]; then docker tag $CI_REGISTRY/$CI_PROJECT_PATH:latest $CI_REGISTRY/$CI_PROJECT_PATH:$(cat VERSION); docker push $CI_REGISTRY/$CI_PROJECT_PATH:$(cat VERSION); fi
